const styles = {
  layout: {
    overflow: "hidden",
    height: "100%",
  },
  sider: {
    borderRight: "1px solid #d9d9d9",
    background: "#ffffff",
    transition: "all 0.2s",
    overflow: "auto",
    zIndex: 2,
  },
  siderHeader: (collapsed: boolean) => ({
    height: 80,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "bold",
    fontSize: collapsed ? 20 : 22,
    color: "#000",
  }),
  header: {
    padding: "0 30px",
    display: "flex",
    height: 70,
    alignItems: "center",
    justifyContent: "space-between",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    borderBottom: "1px solid #d9d9d9",
    background: "#ffffff",
    overflow: "hidden",
  },
  avatar: {
    backgroundColor: "#FF0000",
    marginLeft: "15px",
  },
  arrowButtonMenu: (collapsed: boolean) => ({
    position: "absolute",
    left: collapsed ? "64px" : "315px",
    zIndex: 99,
    height: 30,
    width: 30,
    borderRadius: 10,
    border: "1px solid #d9d9d9",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    transition: "left 0.3s ease",
    backgroundColor: "#ffffff",
  }),
  content: {
    margin: 0,
    display: "flex",
    flexDirection: "column",
    background: "#ffffff",
    color: "#000",
    overflow: "hidden",
  },
  contentInner: {
    background: "#ffffff",
    padding: 24,
    borderRadius: 8,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.1)",
    width: "100%",
    overflow: "auto",
    maxHeight: "calc(100vh - 160px)",
  },
  titleHeader: {
    color: "#333",
  },
  menu: {
    backgroundColor: "#ffffff",
    overflowY: "auto",
  },
  menuItem: {
    backgroundColor: "#ffffff",
    color: "#000",
  },
  menuItemSelected: {
    background: "rgba(255, 0, 0, 0.14)",
    color: "#FF0000",
    border: "0.25px solid rgba(255, 0, 0, 0.35)",
  },
};

export default styles;